# Generated by Django 5.2.5 on 2025-08-20 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_app', '0004_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardmember',
            options={'verbose_name': 'Board Member', 'verbose_name_plural': 'Board Members'},
        ),
        migrations.AlterField(
            model_name='board',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the board was created.'),
        ),
        migrations.AlterField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of the board (via BoardMember relation).', related_name='boards', through='kanban_app.BoardMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='owner',
            field=models.ForeignKey(help_text='User who created and owns the board.', on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(help_text='The board this membership belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to='kanban_app.board'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user joined the board.'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member of the board.', on_delete=django.db.models.deletion.CASCADE, related_name='board_memberships', to=settings.AUTH_USER_MODEL),
        ),
    ]
